### ISSUE TITLE
Tutorial on how to run custom scripts

### ISSUE THREAD

**Issue by alexsteve647** [TheMorc/LS09-things#1]
Here is link on how to run custom scripts in patched `Farming Simulator 2009` engine: [Link](https://github.com/alexsteve647/LS09Cracked)

**Comment by alexsteve647** [comment]
Also now you can port `LS2008 Multiplayer` mod to `LS2009`.

**Comment by alexsteve647** [comment]
Looks like no one will answer

**Comment by TheMorc** [comment]
I don't think you even asked something 🙃

**Comment by alexsteve647** [comment]
I thought you didn't even read it
